// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZX4MvqixgmCX6fUEWw4FYBcUO94TSr0Y',
    appId: '1:250184362539:web:c1f60e046e6e8fc466986e',
    messagingSenderId: '250184362539',
    projectId: 'production-todo-cf9e1',
    authDomain: 'production-todo-cf9e1.firebaseapp.com',
    storageBucket: 'production-todo-cf9e1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNtmfF-fOJNHAGRDewGeiCqY9Y-1VXAuc',
    appId: '1:250184362539:android:41ccdbd33537712566986e',
    messagingSenderId: '250184362539',
    projectId: 'production-todo-cf9e1',
    storageBucket: 'production-todo-cf9e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuZaYJUbqoCGgB1Ok8iGW5kl6RlxRDPYY',
    appId: '1:250184362539:ios:6b9ed60b5648324a66986e',
    messagingSenderId: '250184362539',
    projectId: 'production-todo-cf9e1',
    storageBucket: 'production-todo-cf9e1.firebasestorage.app',
    iosBundleId: 'com.example.proTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuZaYJUbqoCGgB1Ok8iGW5kl6RlxRDPYY',
    appId: '1:250184362539:ios:6b9ed60b5648324a66986e',
    messagingSenderId: '250184362539',
    projectId: 'production-todo-cf9e1',
    storageBucket: 'production-todo-cf9e1.firebasestorage.app',
    iosBundleId: 'com.example.proTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZX4MvqixgmCX6fUEWw4FYBcUO94TSr0Y',
    appId: '1:250184362539:web:c051b4ecc6c6537966986e',
    messagingSenderId: '250184362539',
    projectId: 'production-todo-cf9e1',
    authDomain: 'production-todo-cf9e1.firebaseapp.com',
    storageBucket: 'production-todo-cf9e1.firebasestorage.app',
  );
}
